name: Linux

on: [push]

jobs:
    build-linux:
        strategy:
            matrix:
                qt_version: [5.15.2]

        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install Qt
          uses: jurplel/install-qt-action@v3
          with:
              version: ${{matrix.qt_version}}
              cache: true
              cache-key-prefix: QtCache

        - name: Install brew
          run: |
              sudo apt-get install build-essential procps curl file git
              test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
              test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
              test -r ~/.bash_profile && echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> ~/.bash_profile
              echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> ~/.profile

        - name: Install Envs
          run: |
              brew install opencascade
              brew install orocos-kdl
              brew install assimp
              brew install googletest
              brew install fmt
              brew install eigen
              brew install boost
              brew install ompl
              brew install ninja

        - name: Get count of CPU cores
          uses: SimenB/github-actions-cpu-cores@v1
          id: cpu-cores

        - name: Ninja build
          working-directory: ${{github.workspace}}
          run: |
              cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release \
              -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang \
              -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -B${{github.workspace}}/build/Mac_Ninja_Release \
              -S${{github.workspace}} -G Ninja
              cmake -B build
              cmake --build ${{github.workspace}}/build/Mac_Ninja_Release --config Release --target all --

        - name: Execute ninja Unit Tests
          working-directory: ${{github.workspace}}/build/Mac_Ninja_Release
          run: |
              ctest -T test -R





