name: Linux

on: [push]

jobs:
    build-linux:
        strategy:
            matrix:
                qt_version: [5.15.2]

        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2


        - name: Install brew
          run: |
              sudo apt-get install build-essential procps curl file git
              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
              echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> $HOME/.bash_profile

        - name: Install Envs
          run: |
              brew install hello


        - name: Get count of CPU cores
          uses: SimenB/github-actions-cpu-cores@v1
          id: cpu-cores

        - name: Install Qt
          uses: jurplel/install-qt-action@v3
          with:
              version: ${{matrix.qt_version}}
              cache: true
              cache-key-prefix: QtCache
        - name: Ninja build
          working-directory: ${{github.workspace}}
          run: |
              cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release \
              -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang \
              -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -B${{github.workspace}}/build/Mac_Ninja_Release \
              -S${{github.workspace}} -G Ninja
              cmake -B build
              cmake --build ${{github.workspace}}/build/Mac_Ninja_Release --config Release --target all --

        - name: Execute ninja Unit Tests
          working-directory: ${{github.workspace}}/build/Mac_Ninja_Release
          run: |
              ctest -T test -R





