name: macOS

on: [push]

jobs:
    build-macos:
        runs-on: macos-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2

        # We can alse use the following to install Qt, to decrese cache size
        - name: Cache Qt
          id: qt-cache
          uses: actions/cache@v2
          with:
            path: /home/runner/work/RobotFramework/Qt
            key: QtCache-linux-6.5.1
            restore-keys: |
              QtCache-linux-6.5.1

        - name: Install Qt
          if: steps.qt-cache.outputs.cache-hit != 'true'
          uses: jurplel/install-qt-action@v3
          with:
            version: 6.5.1
            cache: true
            cache-key-prefix: QtCache

        - name: Cache brew env
          id: env-cache-mac
          uses: actions/cache@v2
          with:
           path: |
             /usr/local/Cellar/*
           key: brew-cache-mackey
           restore-keys: |
             brew-cache-mackey

        - name: Install brew and dependencies
          if: steps.env-cache-mac.outputs.cache-hit != 'true'
          run: |
            brew install assimp
            brew install ninja
            ls /usr/local/Cellar

        - name: Build Release
          working-directory: ${{github.workspace}}
          run: |
            cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_CXX_STANDARD=20 \
            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang \
            -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -B${{github.workspace}}/build/Mac_Ninja_Release \
            -S${{github.workspace}} -G Ninja
            cmake -B build
            cmake --build ${{github.workspace}}/build/Mac_Ninja_Release --config Release --target all --

        # - name: Execute Unit Tests Release
        #   working-directory: ${{github.workspace}}/build/Mac_Ninja_Release
        #   run: |
        #     ctest -T test -R