name: Windows

on: [push]

jobs:
    build-windows-msvc:
        strategy:
            matrix:
                occ_version: [7.7.0]

        runs-on: windows-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Install Qt
          uses: jurplel/install-qt-action@v3
          with:
              cache: true
              cache-key-prefix: QtCache

        - name: vcpkg build
          uses: johnwason/vcpkg-action@v5
          id: vcpkg
          with:
            pkgs: |
              opencascade boost |
              assimp eigen3 fmt googletest ompl orocos-kdl ninja
            triplet: x64-windows-release
            revision: master
            token: ${{ github.token }}

        # - name: Build Release
        #   working-directory: ${{github.workspace}}
        #   run: |
        #     cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_CXX_STANDARD=20 \
        #     -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=cl.exe \
        #     -DCMAKE_CXX_COMPILER=cl.exe -B${{github.workspace}}/build/Mac_Ninja_Release \
        #     -S${{github.workspace}} -G Ninja
        #     cmake -B build
        #     cmake --build ${{github.workspace}}/build/Mac_Ninja_Release --config Release --target all --

        # - name: Execute Unit Tests Release
        #   working-directory: ${{github.workspace}}/build/Mac_Ninja_Release
        #   run: |
        #     ctest -T test -R