name: Linux

on: [push]

jobs:
    build-linux:
        strategy:
            matrix:
                qt_version: [5.15.2]

        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2


        - name: Install brew
          run: |
            sudo apt-get install build-essential procps curl file git
            sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
            test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
            test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
            test -r ~/.profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
            echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
            source ~/.profile



        - name: Install Envs
          run: |
            echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
            source ~/.profile
            brew install googletest
            brew install fmt
            brew install eigen
            brew install ninja
            brew install boost-uuid



        - name: Get count of CPU cores
          uses: SimenB/github-actions-cpu-cores@v1
          id: cpu-cores


        - name: Ninja build
          working-directory: ${{github.workspace}}
          run: |
            echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
            source ~/.profile
            cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release \
            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang \
            -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -B${{github.workspace}}/build/Mac_Ninja_Release \
            -S${{github.workspace}}
            cmake -B build
            cmake --build ${{github.workspace}}/build/Mac_Ninja_Release --config Release --target all --






