name: macOS

on: [push]

jobs:
    build-macos:
        runs-on: macos-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install Qt
          uses: jurplel/install-qt-action@v3
          with:
            version: 6.5.1
            cache: true
            cache-key-prefix: QtCache

        - name: Cache brew dependencies
          id: env-cache
          uses: actions/cache@v3
          with:
            path: |
              /usr/local/Cellar/googletest
              /usr/local/Cellar/assimp
              /usr/local/Cellar/ompl
              /usr/local/Cellar/ninja
            key: ${{ runner.os }}-brew-${{ hashFiles('**/ci_linux.yml') }}
            restore-keys: |
              ${{ runner.os }}-brew-

        - name: Install brew and dependencies
          if: steps.env-cache.outputs.cache-hit != 'true'
          run: |
              brew install googletest
              brew install assimp
              brew install ompl
              brew install ninja

        - name: Build Release
          working-directory: ${{github.workspace}}
          run: |
            cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_CXX_STANDARD=20 \
            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang \
            -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -B${{github.workspace}}/build/Mac_Ninja_Release \
            -S${{github.workspace}} -G Ninja
            cmake -B build
            cmake --build ${{github.workspace}}/build/Mac_Ninja_Release --config Release --target all --

        - name: Execute Unit Tests Release
          working-directory: ${{github.workspace}}/build/Mac_Ninja_Release
          run: |
            ctest -T test -R