name: macOS

on: [push]

jobs:
    build-macos:
        runs-on: macos-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install Qt
          uses: jurplel/install-qt-action@v3
          with:
            version: '6.5.1'
            cache: true
            cache-key-prefix: QtCache

        - name: Install Envs
          run: |
            brew install boost-uuid
            brew install orocos-kdl
            brew install googletest
            brew install fmt
            brew install eigen
            brew install ninja

        - name: Get count of CPU cores
          uses: SimenB/github-actions-cpu-cores@v1
          id: cpu-cores

        - name: Build Release
          working-directory: ${{github.workspace}}
          run: |
            cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release \
            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang \
            -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -B${{github.workspace}}/build/Mac_Ninja_Release \
            -S${{github.workspace}} -G Ninja
            cmake -B build
            cmake --build ${{github.workspace}}/build/Mac_Ninja_Release --config Release --target all --

        - name: Execute Unit Tests Release
          working-directory: ${{github.workspace}}/build/Mac_Ninja_Release
          run: |
            ctest -T test -R

        - name: Build Debug
          working-directory: ${{github.workspace}}
          run: |
            cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Debug \
            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang \
            -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -B${{github.workspace}}/build/Mac_Clang_Debug \
            -S${{github.workspace}} -G Ninja
            cmake -B build
            cmake --build ${{github.workspace}}/build/Mac_Clang_Debug --config Debug --target all --

        - name: Execute Unit Tests Debug
          working-directory: ${{github.workspace}}/build/Mac_Clang_Debug
          run: |
            ctest -T test -R
