name: macOS

on:
    [push]

jobs:
    clang-release:
        runs-on: macos-latest
        env:
            targetName: RobotFrame
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        # - name: Install Qt
        #   uses: jurplel/install-qt-action@v3
        #   with:
        #     version: 6.5.1
        #     cache: true
        #     cache-key-prefix: QtCache

        - name: Install brew and dependencies
          run: |
            brew install googletest
            brew install llvm
            brew install ninja
        # brew install assimp
        # brew install ompl
        # brew install opencascade
        # brew install orocos-kdl
        # brew install mesa
        # brew install spdlog
        # brew install eigen
        # brew install fmt

        # - name: Install boost
        #   uses: MarkusJx/install-boost@v2.4.5
        #   id: install-boost
        #   with:
        #     # REQUIRED: Specify the required boost version
        #     # A list of supported versions can be found here:
        #     # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
        #     boost_version: 1.83.0
        #     # OPTIONAL: Specify a platform version
        #     platform_version: 14
        #     # OPTIONAL: Specify a custom install location
        #     boost_install_dir: ${{github.workspace}}

        - name: Build Release
          working-directory: ${{github.workspace}}
          run: |
            export PATH="/usr/local/opt/llvm/bin:$PATH"
            cmake \
            -DBoost_INCLUDE_DIR=${{steps.install-boost.outputs.BOOST_ROOT}}/include \
            -DBoost_LIBRARY_DIRS=${{steps.install-boost.outputs.BOOST_ROOT}}/lib \
            -DCMAKE_BUILD_TYPE:STRING=Release \
            -DCMAKE_CXX_STANDARD=20 \
            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE \
            -DCMAKE_C_COMPILER:FILEPATH=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -B${{github.workspace}}/build/Mac_Ninja_Release \
            -S${{github.workspace}} -G Ninja
            cmake --build ${{github.workspace}}/build/Mac_Ninja_Release --config Release --target all --


        # CPU cost on mac is too expensive and the test errors are not able to reported. Forbid now.
        - name: Execute Unit Tests Release
          working-directory: ${{github.workspace}}/build/Mac_Ninja_Release
          run: |
            ctest -T test -j 4 -V
