name: Test

on: [push]

jobs:
    build-windows-msvc:
        runs-on: windows-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Configure Compiler
          uses: ilammy/msvc-dev-cmd@v1

        - name: Install Qt
          uses: jurplel/install-qt-action@v3
          with:
            version: 5.15.2
            cache: true
            cache-key-prefix: QtCache

        - name: vcpkg build
          uses: johnwason/vcpkg-action@v5
          id: vcpkg
          with:
            pkgs: ompl eigen3 spdlog
            triplet: x64-windows-release
            token: ${{ github.token }}

        - name: Cache Boost
          id: cache-boost
          uses: actions/cache@v3
          with:
            path: boost_1_84_0-msvc-14.3-64.exe
            key: boost_1_84_0-msvc

        - name: Download Boost
          if: steps.cache-boost.outputs.cache-hit != 'true'
          uses: carlosperate/download-file-action@v2
          with:
            file-url: 'https://jaist.dl.sourceforge.net/project/boost/boost-binaries/1.84.0/boost_1_84_0-msvc-14.3-64.exe'

        - name: Install Boost
          run: |
            Start-Process -FilePath .\boost_1_84_0-msvc-14.3-64.exe -ArgumentList '/SILENT', '/SP-', '/SUPPRESSMSGBOXES', '/DIR=C:\boost' -NoNewWindow -Wait

        - name: Set BOOST_ROOT environment variable
          run: |
            echo "BOOST_ROOT=C:\boost" | Out-File -FilePath $env:GITHUB_ENV -Append

        - name: Build Release
          working-directory: ${{github.workspace}}
          run: |
            cmd.exe /k "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
            cmake --version
            cmake --no-warn-unused-cli `
            -DCMAKE_TOOLCHAIN_FILE=D:\a\OccDemo\OccDemo/vcpkg/scripts/buildsystems/vcpkg.cmake `
            -DVCPKG_TARGET_TRIPLET=x64-windows-release `
            -DVCPKG_MANIFEST_MODE=OFF `
            -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_CXX_STANDARD=20 `
            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=cl.exe `
            -DCMAKE_CXX_COMPILER=cl.exe -B${{github.workspace}}/build/win_msvc_release `
            -S${{github.workspace}} -G Ninja
            cmake --build ${{github.workspace}}/build/win_msvc_release --config Release --target all --

        - name: Execute Unit Tests Release
          working-directory: ${{github.workspace}}/build/win_msvc_release
          run: |
            ctest -T test -R


