name: Test

on: [push]

jobs:
    build-windows-msvc:
        strategy:
            matrix:
                occ_version: [7.7.0]

        runs-on: windows-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Install Qt
          uses: jurplel/install-qt-action@v3
          with:
            version: 5.15.2
            cache: true
            cache-key-prefix: QtCache

        - name: Install Vcpkg
          shell: powershell
          run: |
            git clone https://github.com/Microsoft/vcpkg.git
            cd vcpkg
            .\bootstrap-vcpkg.bat
            vcpkg integrate install
            Add-Content -Path .\triplets\x64-windows.cmake -Value "set(VCPKG_BUILD_TYPE release)"
            vcpkg install assimp --triplet x64-windows
            rm rf buildtrees
            rm rf downloads
            rm rf packages
            rm rf ports
            rm rf triplets
            ls

        - name: Cache Vcpkg Packages
          uses: actions/cache@v3
          with:
            path: vcpkg/packages
            key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg/vcpkg.json') }}

        # - name: Build Release
        #   working-directory: ${{github.workspace}}
        #   run: |
        #     cmake --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_CXX_STANDARD=20 \
        #     -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=cl.exe \
        #     -DCMAKE_CXX_COMPILER=cl.exe -B${{github.workspace}}/build/Mac_Ninja_Release \
        #     -S${{github.workspace}} -G Ninja
        #     cmake -B build
        #     cmake --build ${{github.workspace}}/build/Mac_Ninja_Release --config Release --target all --

        # - name: Execute Unit Tests Release
        #   working-directory: ${{github.workspace}}/build/Mac_Ninja_Release
        #   run: |
        #     ctest -T test -R