name: Test

on: [push]

jobs:
    build-windows-msvc:
        runs-on: windows-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Configure Compiler
          uses: ilammy/msvc-dev-cmd@v1

        - name: Install Qt
          uses: jurplel/install-qt-action@v3
          with:
            version: 5.15.2
            cache: true
            cache-key-prefix: QtCache

        - name: vcpkg build
          uses: johnwason/vcpkg-action@v5
          id: vcpkg
          with:
            pkgs: ompl eigen3 spdlog
            triplet: x64-windows-release
            token: ${{ github.token }}

        - name: Build Release
          working-directory: ${{github.workspace}}
          run: |
            cmd.exe /k "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64

            cmake --version
            cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_CXX_STANDARD=20 `
            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=cl.exe `
            -DCMAKE_CXX_COMPILER=cl.exe -B${{github.workspace}}/build/win_msvc_release `
            -S${{github.workspace}} -G Ninja

            cmake -B build
            cmake --build ${{github.workspace}}/build/win_msvc_release --config Release --target all --

        - name: Execute Unit Tests Release
          working-directory: ${{github.workspace}}/build/win_msvc_release
          run: |
            ctest -T test -R


