name: Test

on: [push]

jobs:
    build-windows-msvc:
        runs-on: windows-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Configure Compiler
          uses: ilammy/msvc-dev-cmd@v1

        - name: Install Qt
          uses: jurplel/install-qt-action@v3
          with:
            version: 5.15.2
            cache: true
            cache-key-prefix: QtCache

        - name: Cache OpenCascade archive
          id: cache-occ
          uses: actions/cache@v3
          with:
              path: occt-vc143-64.zip
              key: occ-7.8.0

        - name: Download OpenCascade
          if: steps.cache-occ.outputs.cache-hit != 'true'
          uses: carlosperate/download-file-action@v2
          with:
              file-url: 'https://github.com/Open-Cascade-SAS/OCCT/releases/download/V7_8_0/occt-vc143-64.zip'

        - name: Extract OpenCascade
          run: 7z x occt-vc143-64.zip

        - name: Cache Assimp archive
          id: cache-assimp
          uses: actions/cache@v3
          with:
              path: assimp-5.3.1.zip
              key: assimp-5.3.1

        - name: Download Assimp
          if: steps.cache-assimp.outputs.cache-hit != 'true'
          uses: carlosperate/download-file-action@v2
          with:
              file-url: 'https://www.fougue.pro/share/bin/assimp-5.3.1.zip'
              sha256: 'b6097488fa5b7a0cc610e8258e74aaa9552b48a13bc8680eedd66512d788e64f'

        - name: Extract Assimp
          run: 7z x assimp-5.3.1.zip

        - name: vcpkg build
          uses: johnwason/vcpkg-action@v5
          id: vcpkg
          with:
            pkgs: ompl eigen3 spdlog
            triplet: x64-windows-release
            token: ${{ github.token }}

        - name: Build Release
          working-directory: ${{github.workspace}}
          run: |
            cmd.exe /k "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
            cmake --version
            cmake --no-warn-unused-cli `
            -DCMAKE_TOOLCHAIN_FILE=D:\a\OccDemo\OccDemo/vcpkg/scripts/buildsystems/vcpkg.cmake `
            -DVCPKG_TARGET_TRIPLET=x64-windows-release `
            -DVCPKG_MANIFEST_MODE=OFF `
            -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_CXX_STANDARD=20 `
            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=cl.exe `
            -DCMAKE_CXX_COMPILER=cl.exe -B${{github.workspace}}/build/win_msvc_release `
            -DOpenCASCADE_DIR=${{github.workspace}}/occt-vc143-64 `
            -Dassimp_DIR=${{github.workspace}}/assimp-5.3.1/lib/cmake/assimp-5.3 `
            -S${{github.workspace}} -G Ninja
            cmake --build ${{github.workspace}}/build/win_msvc_release --config Release --target all --

        - name: Execute Unit Tests Release
          working-directory: ${{github.workspace}}/build/win_msvc_release
          run: |
            ctest -T test -R


